---
output_format:
  pdf_document:
    keep_tex: true
---

## Selecting seed sounds

We selected inanimate categories of sounds because they were less likely to have lexicalized onomatopoeic forms already in English, and they were assumed to be less familiar and more difficult to imitate. We used an odd-one-out norming procedure (_N_ = 105 participants) to reduce an initial set of 36 sounds in 6 categories to a final set of 16 "seed" sounds: 4 sounds in each of 4 categories. The four final categories included: water, glass, tear, zipper.

## Collecting imitations

Participants were paid to participate in an online version of the children's game of "Telephone". The instructions informed participants that they would hear some sound and their task is to reproduce it as accurately as possible using their computer microphone. Participants listened to and imitated 4 sounds. Participants received one sound from each of the four categories of sounds drawn at random such that participants were unlikely to hear the same person more than once. Imitations were monitored by an experimenter to catch any gross errors in recording before they were passed on to the next generation of imitators. The experimenter also blocked sounds that violated the rules of the experiment, e.g., by saying something in English.

## Matching imitations to seeds

Participants listened to imitations and guessed which seeds they came from. By varying the relationship between the imitation and the options presented to each participant, we were able to assess the extent to which the imitations retained categorical as opposed to specific, identifying information.

## Collecting transcriptions of imitations

Participants were instructed to write down what they heard as a word so that the written word would sound as much like the message as possible.

## Matching transcriptions to seeds

Instead of listening to imitations, participants now read a transcription of an imitation, which they were told was an invented word. They were instructed that the word was invented to describe one of four presented sounds, and they had to guess which one.

## Learning transcriptions as category labels
