#!/usr/bin/env bash
make reset
make creating-words.pdf
make creating-words.docx
NAME="${1:-creating-words}"
DIR=submissions/$NAME
mkdir -p $DIR
mv creating-words.pdf $DIR/$NAME.pdf
mv creating-words.docx $DIR/$NAME.docx
make clean
