---
output: pdf_document
---

```{r config, include=FALSE}
library(knitr)

opts_chunk$set(
  echo=FALSE,
  message=FALSE,
  warning=FALSE,
  results="hide",
  cache=TRUE
)

sapply(list.files("R", "*.R", full.names = TRUE), read_chunk)
```

```{r setup, include=FALSE}
```

```{r stability, include=FALSE}
```

```{r matching, include=FALSE}
```

```{r learning, include=FALSE}
```

```{r dendrogram, fig.width=4, fig.height=3.5}
gg_dendrogram
```

```{r similarity-judgments, fig.width=4, fig.height=4}
gg_similarity_judgments
```

```{r algorithmic-similarity, fig.width=4, fig.height=4}
gg_algo_similarity +
  theme(legend.position = c(0.45, 0.9))
```

```{r algorithmic-similarity-types, fig.width=6, fig.height=4}
gg_algo_compare
```

```{r comparing-similarities, fig.width=4, fig.height=4}
gg_comparing_similarities
```

```{r transcription-distance, fig.width=4, fig.height=4}
gg_distance
```

```{r transcription-of-seeds-distance, fig.width=6, fig.height=4}
gg_seed_distance
```

```{r matching-questions, fig.width=6, fig.height=4}
grid.arrange(
  read_graphviz("true-seed", "wordsintransition"),
  read_graphviz("category-match", "wordsintransition"),
  read_graphviz("specific-match", "wordsintransition"),
  ncol = 1
)
```

```{r matching-accuracies, fig.width=6, fig.height=3.5}
grid.arrange(
  gg_match_to_seed,
  gg_match_transcriptions + theme(axis.title.y = element_blank()),
  nrow = 1
)
```

```{r matching-imitations, fig.width=4, fig.height=4}
gg_match_to_seed
```

```{r matching-transcriptions, fig.width=4, fig.height=4}
gg_match_transcriptions
```

```{r matching-transcriptions-of-seeds, fig.width=6, fig.height=4}
gg_seed_matching
```

```{r learning-transcriptions, fig.width=6, fig.height=3.5}
grid.arrange(
  rt_plot,
  gg_transition + theme(axis.title.y = element_blank()),
  nrow = 1,
  widths = c(0.6, 0.4)
)
```

```{r learning-rts, fig.width=4, fig.height=4}
rt_plot +
  theme(legend.position = c(0.55, 0.9))
```

```{r learning-generalization, fig.width=4, fig.height=4}
gg_transition +
  theme(legend.position = c(0.45, 0.9))
```

```{r learning-performance-ceiling, fig.width=4, fig.height=4}
gg_lsn_performance_ceiling +
  theme(legend.position = c(0.45, 0.9))
```

```{r learning-transcriptions-of-seeds, fig.width=4, fig.height=4}
gg_seed_rt_plot +
  theme(legend.position = c(0.55, 0.9))
```