---
output: word_document
---

```{r config, include=FALSE}
library(knitr)
library(magrittr)
sapply(list.files("../R", "*.R", full.names = TRUE), read_chunk)
```


```{r setup, include=FALSE, cache=FALSE}
```

```{r stability, include=FALSE}
```

```{r helmert-contrasts, results="asis", echo=FALSE}
broom::tidy(acoustic_similarity_comparison_mod) %>%
  knitr::kable(caption = "Model results predicting algorithmic acoustic similarity from type of pairwise comparison. The six types of pairwise comparisons depicted in Fig. S2 were contrast coded for the linear model with Helmert contrasts. The intercept term corresponds to the overall acoustic similarity along consecutive generations of imitations within individual transmission chains. The first Helmert contrast compares the acoustic similarities of consecutive generation imitations to all other comparisons within the same transmission chain. The second contrast compares the similarity among imitations from an individual transmission chains to the similarity of all imitations from a given seed sound (between chains). The third contrast compares the similarity among imitations of a given seed sound to imitations of the same category. The fourth contrast comparse within category similarity to between category similarity, with imitations sampled from the same generation. The fifth contrast compares all other contrast types to the least similar type of comparisons, where between category imitations from consecutive generations are compared.")
```