---
output: pdf_document
header-includes:
  - \usepackage{caption}
  - \DeclareCaptionLabelFormat{si-fig}{#1#2}
  - \captionsetup[figure]{labelformat=si-fig,name=Figure S}
---

```{r config, include=FALSE}
library(knitr)

opts_chunk$set(
  echo=FALSE,
  message=FALSE,
  warning=FALSE,
  results="hide",
  fig.align="center",
  cache=TRUE,
  autodep=TRUE
)

sapply(list.files("../R", "*.R", full.names = TRUE), read_chunk)
```

```{r setup, include=FALSE, cache=FALSE}
```

```{r stability, include=FALSE}
```

```{r learning, include=FALSE}
```

```{r matching, include=FALSE}
```

```{r figS1, fig.width=6.5, out.width="6.5in", fig.height=8, out.height="8in", fig.cap="Seed selection norming procedure. Results of the norming procedure designed to reduce the initial set of 36 seed sounds in six categories to a final set of 16 sounds in four categories. A. Results of the first round of odd-one-out norming. After collecting these responses, two sounds that were the most different from the others in each category were removed, and the norming procedure was conducted again. B. Results of the second round of odd-one-out norming. After collecting these responses, four categories of sounds were selected for use as seeds in the transmission chain experiment."}
grid.arrange(
  gg_seed_selection_round_1 + ggtitle("A."),
  gg_seed_selection_round_2 + ggtitle("B."),
  nrow = 1
)
```

```{r figS2, fig.width=5, out.width="5in", fig.height=8, out.height="8in", fig.cap="\\textbf{Algorithmic measures of acoustic distance using MFCCs.} \\textbf{a.} Average acoustic distance between pairs of sounds grouped by type of pairwise comparison. \\textbf{b.} Change in algorithmic acoustic distance over generations of imitations. \\textbf{c.} Correlation between similarity judgments and algorithmic measures."}
grid.arrange(
  gg_algo_compare,
  gg_algo_similarity,
  gg_comparing_similarities
)
```

```{r figS3, fig.width=5, out.width="5in", fig.height=8, out.height="8in", fig.cap="\\textbf{Alternative measures of orthographic distance.} \\textbf{a.} Percentage of exact string matches per imitation. \\textbf{b.} Orthographic distance separated by whether there was any agreement among the transcriptions of a given imitation. \\textbf{c.} Change in the average length of the longest substring match."}
grid.arrange(
  gg_exact_matches,
  gg_string_distance,
  gg_length_plot,
  ncol = 1
)
```

```{r figS4, fig.cap="\\textbf{Error rates for category learning experiment.} Mean number of errors per block of 24 trials, showing that accuracy performance was high even in the first block of trials, and quickly reached ceiling after the first block."}
gg_lsn_performance_ceiling
```

```{r figS5, fig.width=5, out.width="5in", fig.height=8, out.height="8in", fig.cap="\\textbf{Results of transcriptions directly of seed sounds.} As a control, we also had participants generate ``transcriptions'' directly from the seed sounds. \\textbf{a.} Transcriptions of environmental sounds were the most variable in terms of orthographic distance. \\textbf{b.} The most frequent of the transcriptions were the easiest to match back to the original seeds. \\textbf{c.} When learning these transcriptions as category labels, participants were the fastest to learn them in the first block, but they did not generalize to new category members as fast as transcriptions taken from last generation imitations."}
grid.arrange(
  gg_seed_distance,
  gg_seed_rt_plot,
  gg_seed_matching,
  ncol = 1
)
```
